### ISSUE TITLE
Cardano Meet-Up - 24th July 2021

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Catalyst-Eastern-Hemisphere-Co-Ordination#5]
### ETH Ideation #2
This Issue tracks progress on ETH Ideation and contains links to the documentation

### Eastern Hemisphere Cardano Meet up - Hosts & Translators #4
This Issue tracks progress on Hosts & Translators and contains links to the documentation

### Set-up Cardano Meet-Up Project Board #1
This Issue documents the setup of the Cardano Meet-Ups Project Board (https://github.com/Catalyst-Swarm/Catalyst-Eastern-Hemisphere/projects/1 ) 

- [x] Would the EH Cardano Meetup like to document their activities in a GitBook
- [x] Would the EH Cardano Meetup like to track their activities in GitHub

### GitBook internationalization
https://docs.gitbook.com/features/internationalization

![2021-07-24 (5)](https://user-images.githubusercontent.com/25156451/126909799-193671e8-eca9-45cc-b635-a7b34d5afe0a.png)

## Notes of the meeting
- These notes are a summary of what was said in sequential order. 
- Please note that throughout I have substituted the word interpreter for translator (which is the correct term in this context as Skip noted)

### Yan Tirta
To address the needs of the Eastern Hemisphere we have developed a step-by-step action plan. This creates Breakout rooms for each local community - Japan, Indonesia, Korea and starts this Thursday 29th 2021. This meeting aims to iron out any unseen issues
### Greg Hall
An opportunity is needed to engage with Catalyst Town Hall issues in the 24 hours after it airs each Wednesday. We will discover how many developers, enthusiasts we have in an English speaking break out room. We will listen and learn
The optimum times are between UTC 6 and 12 for Hong Kong, Singapore, Japan, Vietnam, Indonesia, Australia. We hope to reinvigorate activity in Japan. And talk about people’s backgrounds - what people want, people think - take it from there.
A 5-minute intro which is just as a recap of TH - its headlines.

### Tim O'Brien
The Eastern Town Hall will be something that will grow over time. By letting the community build the agenda. In Vietnam we have a younger generation. There is a lack of direction - but a strong group interested in Blockchain technology. We can offer them a valuable service. We should wait and see who turns up.

### Skip (Japan)
Japan skews to older generations. People with money, but who are not knowledgeable. I am an interpreter based in Tokyo. A short summary with headlines could be presented with supplemental materials. Thinking ahead to Thursday I have invited 100 people to the Eastern Town Hall. How can we best prepare people going into Breakout rooms?

### Robert O'Brien
I can attend the main Town Hall as the time is not too bad. 
I'd like to acknowledge the translation work Yuta did for our Fund2 proposal to help engage with the Japanese community.
When I went to an Auckland Meetup there was a mixed range of 20 people, from young guys to 84 years old. From conspiracy theory to "show me the money". I have been interested in Cardano since 2016.. There is quite a broad interest in NZ - an Ex-Treasurer of NZ hold ADA.
I have a Fund 4 - Learning Activation Centre proposal. Helping people to start a social entrepreneurial journey and a social well-being agency. Experience of mentorship programs with quite a lot of experience in achieving positive outcomes. Now a charity.
With respect to Town Hall and Catalyst, some had heard of Catalyst, none had voted - some had staked ADA. Interest has been motivated by the increase in Cardano market capitalization. I met 2 Stakepool Operators - 1 with a desire to reach out to the Turkish ecosystem.

## Felix
We need to have a bit more diversity to ideate solutions at a global level. Eastern Hemisphere Town Halls will be our very first entry point for other communities. The interests and audiences are quite different and varied. There is less homogeneity than the main Town Hall. Different legal structures in each country. The focus should be in each breakout room - with the agenda set in each room. Nothing is fixed - everything is open for ideating. Everyone can speak in their own language. 
To enable them to build bridges when they each community is ready. So, we can gather information on different cultural approaches. A bottom-up approach. We should keep the main room introduction very short because of the burden on interpreters.

## Greg Bell
We could watch the main Town Hall and write a script. If we can get a script the interpreters can use. Such a shared document would help smooth the way.

## Yan Tirta
Having no architecture in the breakout rooms and some architecture for the 5 minute introduction.

## Greg Bell
A short summary of the main Town Hall ? To ease people into the Breakout room

## Felix
Dor suggested Sebastien Guillemot, Mihaela Ulieru - some Cardano heroes in the main room to welcome Eastern Hemisphere Town Hall.

## Greg Bell
It would be good to have an "Around the world" - continuous Town Hall day. Where the main room is like a welcome lobby. Anyone can come and ask any questions. A continuous day of presentations with synchronous translation in each time zone. 

## Felix
We need to focus on the 5 days we have to arrange Eastern Town Hall.

## Yan
What should be the format of the main room ? Should it be a structured summary of main Town Hall or a more informal format ?

## Robert O'Brien
Why not do the summary and pick a time zone and have someone from that their area to run the summary in their own language ?

## Greg Bell
For now we need to see what numbers we can get. We need to see 20 to 40 people turning up before engaging.

## Skip
May I suggest that we use accurate terms, as translation refers to written text, and interpreting is the correct term for live speaking.

## Felix
For the first event we should keep it simple. We want to establish this initiative with you guys.

## Greg
Teams has limited languages (but most major languages).  Unfortunately it will be harder to get attendees to use Teams than it is to get them to use Zoom..

## Skip
Thanks Greg :) - and if we do a townhall recap or summary approach, if translated text in the target language is available, then the host of each language/breakout can present at the beginning of the breakouts ?

## Felix
How can we translate content in the main room and send it to a breakout room ? We can use one graphic in different languages
And this is how I can reach a breakout room.

## Yan
Maybe a video with subtitles ?

## Greg
A static sign is preferable.

## Skip
At an international event - a static slide. One person would copy and paste instructions into the Zoom chat for late arrivals

## Felix
One single slide in several that welcomes and navigates people to their language based breakout rooms. Presented as a screenshare that is visible to everyone joining the main room.

## Greg Bell
Two letter abbreviation of the languages we use after our Zoom names would be helpful.

## Felix
We need to write down a simple text to translate for the single slide.

## Yan
Example Zoom name "Skip - JP" and combine with visual background. Country of residence, name and native language. Put Country abbreviation next to name.

## Felix
Dor asked if he could present or preview Eastren Town Hall in main Town Hall. It would be good if Greg, Yan, Skip, Tim or Robert could present.

## Skip
People need to be familiar with materiel for effective live interpretation. 

## Greg
Slow down [English) speech - use simple words

## Felix
The live interpreters should be an integral part of the design process. Will the interpretation be at the same time or sequential ?

## Greg 
I am beginning to prefer an informal introduction and shift any main Town Hall discussion to each breakout room.

## Skip
Interpreting - simultaneous or continuous ?

## Yan
For Vietnam and Korean - live translation without a transcript would confuse people. The main room should be a transcript only,

## Skip
I prefer dialogue. But a short script may be less of a burden. It is about welcoming people in the space.

## Yan
For the main room we all say the same thing - a simple greeting. So everyone knows what it is all about.

## Skip
A welcome. Then choose your language channels and a few lines of delivery of information.

## SofiH
Here are some options
A) Presentation in 1 language, translated at the same time (language channel)
B) Welcome message and explanation done in each language 
C) Translation per sentence (what felix just did)

## Felix
We should design a very simple agenda description.

## Skip
Translators stay in main room to greet new visitors in their language. I favour A) Presentation in 1 language, translated at the same time (language channel).

Or if it is short - B) Welcome message and explanation done in each language  - which could be cute or try people's patience if it goes on too long.
 
I suggest that we practice it. Do a rehearsal - we can we get the English ? Also pre prepare the Slide and Zoom background

## Felix 
Translators should decide the agenda like a script.

## Yan
English as a starter for first session to keep it simple.

## SofiH
A little bit B then A

## Felix
1. short welcome in Indonesian, Japanese, Vietnamese and an introduction to the live translation item ( C )
2. Intro goes on ( A )

## Skip
Monday 26th July 2021 - 10am  UTC - dress rehearsal

## Who should be the Moderator ?
Greg - nominee - Main room - 10 Thursday night
Robert - nominee - breakout room
Robert - happy to moderate as well - mix things up

# Future Meeting Times
Eastern Hemisphere Town Hall Organization Meetings Each Saturday at 6 am UTC

https://docs.google.com/document/d/17ebf7i7P-BJjJVbaDsBRLMQlJfr3Pyx0dFNeWg_HCkU/edit

# Actions

- For next two weeks Saturday is to do feedback for ETH
- Dry run Monday 10am UTC
- Complete the Cardano Meet-Up - 1 - Preparatory Tasks.
- Write up good introduction
- Thursday night do it
- Saturday feedback
- Use social channels to announce

**Comment by YanTirta** [comment]
Love it Stephen! Really appreciate your contribution! Kinda feels cool? Having someone who also shares good writing (?) and documentation :)

**Comment by stephen-rowan** [comment]
Thanks Yan - I am also building a project board here ( https://github.com/Catalyst-Swarm/Catalyst-Eastern-Hemisphere-Co-Ordination/projects/1 ) - to use when people are ready. But it is probably best to use accessible Google docs at first. It is all useful for future reference and documentation.

**Comment by YanTirta** [comment]
Currently viewing it right now. I second your opinion, it would probably be overwhelming for people. There are connections that are still 404. I reckon because there isn't any content in them yet or is this an issue from my side?

**Comment by stephen-rowan** [comment]
I am just going to use it to track Cardano Meetup meetings and events for now. With links to documentation in context and minutes (like this Issue here). I can transcribe documentation here or to a GitBook I have created - but the Cardano Meetup group should decide its content and direction. I have also started looking at internationalization options for the GitBook.

**Comment by wolstaeb** [comment]
I'm impressed with the effort documenting all this @stephen-rowan. Appreciate it. Can you correct a bit of the summary transcript in my opening comments to reflect the awesome effort Yuta did. I want to make sure that is recognised correctly in any documentation. Thx.

> (?) did the translation for our Fund 5 proposals 

Should read something like "_I'd like to acknowledge the translation work Yuta did for our Fund2 proposal to help engage with the Japanese community._"

Also, but far less important: "I have been interested in **Crypto** since 2016" should read "I have been interested in **Cardano** since 2016." *In* crypto much longer.

**Comment by stephen-rowan** [comment]
Thanks Robert @wolstaeb - I have added your corrections. :)
